{
 "title": "Datapoints Over Time",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mqtt_bucket\")\n  // look over a bit more time so X-axis stretches out\n  |> range(start: -30m)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.device_id == \"kitchen_node_1\")\n  |> filter(fn: (r) =>\n    r._field == \"temp\" or\n    r._field == \"humidity\" or\n    r._field == \"pressure\"\n  )\n  // downsample: one value every 10 seconds instead of every single point\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Pressure over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt_bucket\")\n  |> range(start: -30m)                                // more time\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.device_id == \"kitchen_node_1\")\n  |> filter(fn: (r) => r._field == \"pressure\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Humidity Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"mqtt_bucket\")\n  |> range(start: -30m)                                // more time\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.device_id == \"kitchen_node_1\")\n  |> filter(fn: (r) => r._field == \"humidity\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Temperature over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt_bucket\")\n  |> range(start: -30m)                                // more time\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.device_id == \"kitchen_node_1\")\n  |> filter(fn: (r) => r._field == \"temp\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n"
    }
   ]
  }
 ]
}