{
 "title": "Kitchen Node 1 – Env Data (Temp / Humidity / Pressure)",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "New panFunctional Status (1 = OK)el",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt_bucket\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.device_id == \"kitchen_node_1\")\n  |> filter(fn: (r) => r._field == \"functional\")\n  |> group(columns: [\"device_id\"])\n  |> last()\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _measurement: \"functional_flag\",\n      device_id: r.device_id,\n      _field: \"functional_flag\",\n      _value: if r._value == 1 then 1 else 0\n    }))\n  |> keep(columns: [\"_time\", \"_value\", \"device_id\"])\n"
    }
   ]
  },
  {
   "title": "Connection Type ( 1 = ON)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt_bucket\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.device_id == \"kitchen_node_1\")\n  |> filter(fn: (r) => r._field == \"temp\")          // pick one field as source\n  |> group(columns: [\"device_id\"])                  // drop connection_type as series key\n  |> last()                                         // only the latest row for this device\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _measurement: \"connection_type_flag\",\n      device_id: r.device_id,\n      _field: \"connection_type_flag\",\n      _value: if r.connection_type == \"1\" then 1 else 0\n    }))\n  |> keep(columns: [\"_time\", \"_value\", \"device_id\", \"connection_type\"])\n"
    }
   ]
  },
  {
   "title": "Kitchen Node 1 – Env Data (Temp / Humidity / Pressure)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"mqtt_bucket\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.device_id == \"kitchen_node_1\")\n  |> filter(fn: (r) =>\n    r._field == \"temp\" or\n    r._field == \"humidity\" or\n    r._field == \"pressure\"\n  )\n"
    }
   ]
  }
 ]
}